<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto

namespace Pingpong;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pingpong.Ping</code>
 */
class Ping extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string PingMessage = 1;</code>
     */
    protected $PingMessage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $PingMessage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pingpong::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string PingMessage = 1;</code>
     * @return string
     */
    public function getPingMessage()
    {
        return $this->PingMessage;
    }

    /**
     * Generated from protobuf field <code>string PingMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPingMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->PingMessage = $var;

        return $this;
    }

}

