<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pingpong.proto

namespace Pingpong;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>pingpong.Pong</code>
 */
class Pong extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string PongMessage = 1;</code>
     */
    protected $PongMessage = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $PongMessage
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Pingpong::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string PongMessage = 1;</code>
     * @return string
     */
    public function getPongMessage()
    {
        return $this->PongMessage;
    }

    /**
     * Generated from protobuf field <code>string PongMessage = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPongMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->PongMessage = $var;

        return $this;
    }

}

